# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpt_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1927, 1077)
        Form.setStyleSheet("\n"
"\n"
"#Form{\n"
" background-color:#1D2B3A\n"
"}\n"
"\n"
"#widget{\n"
" background:#1D2B3A\n"
"}\n"
"\n"
"#scrollAreaWidgetContents{\n"
" background:#1D2B3A\n"
"}\n"
"#input_textEdit{\n"
"  border:none;\n"
"}\n"
"\n"
"#scrollArea{\n"
"    border:none;\n"
"}\n"
"\n"
"\n"
"\n"
"#input_frame{\n"
"  background:#2C3E50;\n"
"  border-radius: 15px;  /* 设置圆角 */\n"
"  border:1px\n"
"}\n"
"\n"
"#input_textEdit {\n"
"    background: #2C3E50;  /* 设置背景颜色 */\n"
"    border-radius: 15px;  /* 设置圆角 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.3);  /* 设置浅色半透明的边框 */\n"
"    color: white;  /* 设置字体颜色为白色 */\n"
"    font-family: \'SimSun\', sans-serif;  /* 设置字体为宋体 */\n"
"    font-size: 28px;  /* 设置字体大小为28px */\n"
"}\n"
"\n"
"")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_2.setStyleSheet("#widget_2{\n"
"    background-color:#5b6d81;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.craete_new_frame = QtWidgets.QFrame(self.widget_2)
        self.craete_new_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.craete_new_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.craete_new_frame.setObjectName("craete_new_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.craete_new_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_chat_pushButton = QtWidgets.QPushButton(self.craete_new_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_chat_pushButton.sizePolicy().hasHeightForWidth())
        self.new_chat_pushButton.setSizePolicy(sizePolicy)
        self.new_chat_pushButton.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.new_chat_pushButton.setFont(font)
        self.new_chat_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.new_chat_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #5b6d81;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 24px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅，提供对比 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深，增强效果 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为更深的蓝色，突出按下效果 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果，突出按钮被按下的效果 */\n"
"}\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/GPT/add_24dp_FFFFFF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_chat_pushButton.setIcon(icon)
        self.new_chat_pushButton.setIconSize(QtCore.QSize(36, 36))
        self.new_chat_pushButton.setObjectName("new_chat_pushButton")
        self.verticalLayout.addWidget(self.new_chat_pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.craete_new_frame)
        self.chat_list_frame = QtWidgets.QFrame(self.widget_2)
        self.chat_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_list_frame.setObjectName("chat_list_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.chat_list_frame)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chat_list = QtWidgets.QListView(self.chat_list_frame)
        self.chat_list.setStyleSheet("#chat_list{\n"
"    background-color:#5b6d81;\n"
"    border:none;\n"
"}")
        self.chat_list.setObjectName("chat_list")
        self.verticalLayout_2.addWidget(self.chat_list)
        self.verticalLayout_4.addWidget(self.chat_list_frame)
        self.menu_frame = QtWidgets.QFrame(self.widget_2)
        self.menu_frame.setMinimumSize(QtCore.QSize(0, 400))
        self.menu_frame.setStyleSheet("#menu_frame{\n"
"    border-top:0.5px solid #ffffff;\n"
"}")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.menu_frame)
        self.frame.setStyleSheet("#frame{\n"
"    border_top:1px solid #ffffff;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setPixmap(QtGui.QPixmap(":/GPT/delete_24dp_FFFFFF.svg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #5b6d81;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 20px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅，提供对比 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深，增强效果 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为更深的蓝色，突出按下效果 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果，突出按钮被按下的效果 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.menu_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/GPT/smart_toy_24dp_FFFFFF.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background: transparent;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"/* 如果需要将下拉箭头的颜色也改为白色，可以加上以下样式 */\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"    color: white;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.menu_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/GPT/language_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #5b6d81;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 20px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅，提供对比 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深，增强效果 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为更深的蓝色，突出按下效果 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果，突出按钮被按下的效果 */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.menu_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/GPT/logout_24dp_FFFFFF.svg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #5b6d81;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 20px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅，提供对比 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深，增强效果 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为更深的蓝色，突出按下效果 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果，突出按钮被按下的效果 */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_4.addWidget(self.menu_frame)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setStyleSheet(" background-color:#1D2B3A\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1492, 891))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 685, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(86, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.input_frame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_frame.sizePolicy().hasHeightForWidth())
        self.input_frame.setSizePolicy(sizePolicy)
        self.input_frame.setMinimumSize(QtCore.QSize(1000, 10))
        self.input_frame.setMaximumSize(QtCore.QSize(900, 150))
        self.input_frame.setStyleSheet("")
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.input_frame)
        self.gridLayout.setContentsMargins(10, 10, 5, 10)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_Button = QtWidgets.QPushButton(self.input_frame)
        self.input_Button.setEnabled(True)
        self.input_Button.setAutoFillBackground(False)
        self.input_Button.setStyleSheet("#input_Button{\n"
"    padding: 10px 20px;  /* 设置按钮内边距，增加按钮的大小 */\n"
"}\n"
"\n"
"#input_Button:hover {\n"
"    background-color: #5A9BFB;  /* 鼠标悬停时，按钮背景色变为柔和的亮蓝色 */\n"
"    transform: scale(1.05);  /* 悬停时按钮稍微放大 */\n"
"    border: 2px solid #4C8BF5;  /* 加上边框，增强悬停效果 */\n"
"     border-radius: 15px;  /* 设置圆角 */\n"
"}\n"
"\n"
"#input_Button:pressed {\n"
"    background-color: #3E6CC4;  /* 按钮被按下时背景色变为较暗的蓝色 */\n"
"    transform: scale(0.95);  /* 按钮按下时稍微缩小 */\n"
"    border: 2px solid #2D5B9C;  /* 按钮按下时添加较暗的边框颜色 */ \n"
"    border-radius: 15px;  /* 设置圆角 */\n"
"}")
        self.input_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/GPT/input_circle_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_Button.setIcon(icon1)
        self.input_Button.setCheckable(False)
        self.input_Button.setChecked(False)
        self.input_Button.setAutoRepeat(False)
        self.input_Button.setAutoExclusive(False)
        self.input_Button.setAutoDefault(True)
        self.input_Button.setDefault(True)
        self.input_Button.setFlat(True)
        self.input_Button.setObjectName("input_Button")
        self.gridLayout.addWidget(self.input_Button, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.input_textEdit = QtWidgets.QTextEdit(self.input_frame)
        self.input_textEdit.setObjectName("input_textEdit")
        self.gridLayout.addWidget(self.input_textEdit, 0, 0, 2, 1)
        self.gridLayout_4.addWidget(self.input_frame, 1, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.new_chat_pushButton.setText(_translate("Form", "New Chat"))
        self.pushButton.setText(_translate("Form", "Clear Conversations"))
        self.comboBox.setItemText(0, _translate("Form", "Chat gpt"))
        self.comboBox.setItemText(1, _translate("Form", "文心一言"))
        self.comboBox.setItemText(2, _translate("Form", "智谱清言"))
        self.pushButton_3.setText(_translate("Form", "Update"))
        self.pushButton_4.setText(_translate("Form", "Log Out"))
import gpt_rc
