# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ui_main(object):
    def setupUi(self, ui_main):
        ui_main.setObjectName("ui_main")
        ui_main.resize(1485, 1228)
        ui_main.setStyleSheet("Qwidget{\n"
"  background:#2C3E50;\n"
"  border-radius: 15px;  /* 设置圆角 */\n"
"}\n"
"\n"
"#ui_main{\n"
"  background-color: #1D2B3A\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;  /* 按钮背景为较深的蓝色 */\n"
"    background: none;\n"
"    padding: 2px 5px;\n"
"    margin:0;\n"
"    color: white;  /* 按钮文字颜色为白色 */\n"
"    border: none;  /* 设置细白色边框，并带有一定透明度 */\n"
"    border-radius: 12px;  /* 圆角按钮 */\n"
"    padding: 10px 20px;  /* 设置按钮内边距，增加按钮的大小 */\n"
"    font-size: 16px;  /* 设置字体大小 */\n"
"    font-weight: bold;  /* 设置字体加粗 */\n"
"    transition: background-color 0.3s ease, transform 0.1s ease;  /* 按钮过渡效果 */\n"
"    font-family: \"宋体\"; \n"
"    font-size: 28px;    /* 可以根据需要调整大小 */\n"
"    color: #fff;       /* 设置字体颜色为白色 */\n"
"    font-weight: bold;  /* 设置加粗 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A90E2;  /* 鼠标悬停时，按钮背景色变为亮蓝色 */\n"
"    transform: scale(1.05);  /* 悬停时按钮稍微放大 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2A3B4E;  /* 按钮被按下时背景色变为稍暗的蓝色 */\n"
"    transform: scale(0.95);  /* 按钮按下时稍微缩小 */\n"
"}\n"
"\n"
"\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ui_main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.centralwidget = QtWidgets.QWidget(ui_main)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_menu_cont_frame = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_menu_cont_frame.sizePolicy().hasHeightForWidth())
        self.left_menu_cont_frame.setSizePolicy(sizePolicy)
        self.left_menu_cont_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.left_menu_cont_frame.setMaximumSize(QtCore.QSize(220, 1505))
        self.left_menu_cont_frame.setStyleSheet("#left_menu_cont_frame{\n"
"  background:#2C3E50;\n"
"  border-radius: 15px;  /* 设置圆角 */\n"
"}")
        self.left_menu_cont_frame.setObjectName("left_menu_cont_frame")
        self.leftMenuContainer_2 = QtWidgets.QVBoxLayout(self.left_menu_cont_frame)
        self.leftMenuContainer_2.setContentsMargins(0, 0, 0, 0)
        self.leftMenuContainer_2.setSpacing(0)
        self.leftMenuContainer_2.setObjectName("leftMenuContainer_2")
        self.widget = QtWidgets.QWidget(self.left_menu_cont_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 80))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.open_close_side_bar_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_close_side_bar_btn.sizePolicy().hasHeightForWidth())
        self.open_close_side_bar_btn.setSizePolicy(sizePolicy)
        self.open_close_side_bar_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.open_close_side_bar_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/GPT/account_circle_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_close_side_bar_btn.setIcon(icon)
        self.open_close_side_bar_btn.setIconSize(QtCore.QSize(48, 48))
        self.open_close_side_bar_btn.setObjectName("open_close_side_bar_btn")
        self.verticalLayout_4.addWidget(self.open_close_side_bar_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.leftMenuContainer_2.addWidget(self.widget, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.widget_3 = QtWidgets.QWidget(self.left_menu_cont_frame)
        self.widget_3.setMinimumSize(QtCore.QSize(220, 300))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_page1 = QtWidgets.QPushButton(self.widget_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/GPT/home_24dp_FFFFFF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_page1.setIcon(icon1)
        self.pushButton_page1.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_page1.setCheckable(True)
        self.pushButton_page1.setChecked(True)
        self.pushButton_page1.setAutoRepeat(False)
        self.pushButton_page1.setAutoExclusive(True)
        self.pushButton_page1.setDefault(True)
        self.pushButton_page1.setFlat(True)
        self.pushButton_page1.setObjectName("pushButton_page1")
        self.verticalLayout_3.addWidget(self.pushButton_page1)
        self.pushButton_page2 = QtWidgets.QPushButton(self.widget_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/GPT/explore_24dp_FFFFFF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_page2.setIcon(icon2)
        self.pushButton_page2.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_page2.setObjectName("pushButton_page2")
        self.verticalLayout_3.addWidget(self.pushButton_page2)
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/GPT/question_answer_24dp_FFFFFF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(48, 48))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(20, 700, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.leftMenuContainer_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.left_menu_cont_frame)
        self.mainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setMinimumSize(QtCore.QSize(500, 400))
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        self.horizontalLayout_2.addWidget(self.centralwidget)

        self.retranslateUi(ui_main)
        QtCore.QMetaObject.connectSlotsByName(ui_main)

    def retranslateUi(self, ui_main):
        _translate = QtCore.QCoreApplication.translate
        ui_main.setWindowTitle(_translate("ui_main", "Form"))
        self.pushButton_page1.setText(_translate("ui_main", " 主控制台"))
        self.pushButton_page2.setText(_translate("ui_main", " 结果显示"))
        self.pushButton.setText(_translate("ui_main", " GPT"))
import gpt_rc
