# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2109, 1334)
        Form.setStyleSheet("\n"
"#Form{\n"
" background-color:#0F192A;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    color: white;             /* 设置字体颜色为白色 */\n"
"    background-color: transparent;  /* 设置背景透明 */\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: transparent;  /* 背景透明，保持深蓝色背景可见 */\n"
"    color: white;                   /* 字体颜色为白色 */\n"
"    border: 2px solid #fff7d6;      /* 设置浅蓝色边框，增加视觉效果 */\n"
"    border-radius: 8px;             /* 边框圆角效果，增加现代感 */\n"
"    padding: 5px;                   /* 内边距，避免文字贴边 */\n"
"    font-size: 14px;                /* 设置适当的字体大小 */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #FF4081;          /* 当控件获得焦点时，设置边框颜色为粉红色 */\n"
"    background-color: rgba(0, 0, 0, 0.1); /* 设置获得焦点时的背景为透明黑色，突出显示 */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #1D2B3A;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 16px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为深色 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果 */\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 2px solid rgba(255, 255, 255, 0.3);  /* 半透明白色边框 */\n"
"    border-radius: 10px;                          /* 圆角效果 */\n"
"    background-color: rgba(0, 0, 0, 0.2);        /* 深色背景 */\n"
"    text-align: center;                           /* 中央对齐文本 */\n"
"    color: white;                                 /* 文字颜色为白色 */\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4A90E2;  /* 设置进度条颜色为浅蓝色 */\n"
"    border-radius: 10px;         /* 圆角进度条 */\n"
"    width: 10px;                 /* 设置进度条块的宽度 */\n"
"}\n"
"\n"
"QProgressBar:disabled {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 禁用状态下的背景色 */\n"
"    border-color: rgba(255, 255, 255, 0.2);      /* 禁用状态下的边框色 */\n"
"}\n"
"\n"
"\n"
"QGraphicsView {\n"
"    background-color: #2E3B4E;  /* 设置绘图区背景为浅色 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.2);  /* 设置透明的白色边框 */\n"
"    border-radius: 10px;  /* 圆角边框 */\n"
"    background-image: none;  /* 禁用背景图片 */\n"
"}\n"
"\n"
"QGraphicsView::viewport {\n"
"    background-color: transparent;  /* 设置绘图区域背景为透明 */\n"
"}\n"
"\n"
"\n"
"")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_title = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_title.sizePolicy().hasHeightForWidth())
        self.widget_title.setSizePolicy(sizePolicy)
        self.widget_title.setMinimumSize(QtCore.QSize(20, 80))
        self.widget_title.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_title.setObjectName("widget_title")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_title)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_title)
        self.label.setStyleSheet("/* 针对特定标题Label（推荐通过objectName定位） */\n"
"#label {\n"
"    color: #00FFFF;\n"
"    font-weight: bold;\n"
"    font-size: 48px;  /* 字号可按需调整 */\n"
"}\n"
"\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_17.addWidget(self.widget_title)
        self.widget_22 = QtWidgets.QWidget(Form)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_19 = QtWidgets.QWidget(self.widget_22)
        self.widget_19.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_19.setStyleSheet("#widget_19 {\n"
"    background-color: transparent; /* 半透明背景色，RGBA中的A表示透明度 */\n"
"    border-radius: 10px; /* 可选：给widget添加圆角 */\n"
"    padding: 2px; /* 可选：给widget添加内边距 */\n"
"}\n"
"")
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox = QtWidgets.QGroupBox(self.widget_19)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 340))
        self.groupBox.setMaximumSize(QtCore.QSize(480, 340))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    font-family: \"SimSun\";  /* 设置字体为宋体 */\n"
"    font-size: 32px;       /* 设置字体大小为18px */\n"
"    color:#00FFFF;            /* 设置字体颜色为 */\n"
"    margin-top: 2.3ex;\n"
"    border-top: 2px solid #00c6b7;         /* 隐藏上边框 */\n"
"\n"
"}\n"
"#groupBox::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}\n"
"#groupBox *{}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_16.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.webEngineView_wordcloud = QtWebEngineWidgets.QWebEngineView(self.groupBox)
        self.webEngineView_wordcloud.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_wordcloud.setObjectName("webEngineView_wordcloud")
        self.verticalLayout_16.addWidget(self.webEngineView_wordcloud)
        self.verticalLayout_13.addWidget(self.groupBox)
        self.groupBox_23 = QtWidgets.QGroupBox(self.widget_19)
        self.groupBox_23.setMinimumSize(QtCore.QSize(0, 350))
        self.groupBox_23.setMaximumSize(QtCore.QSize(480, 450))
        self.groupBox_23.setStyleSheet("QGroupBox {\n"
"    font-family: \"SimSun\";  /* 设置字体为宋体 */\n"
"    font-size: 32px;       /* 设置字体大小为18px */\n"
"    color:#00FFFF;            /* 设置字体颜色为 */\n"
"    margin-top: 2.3ex;\n"
"    border-top: 2px solid #00c6b7;         /* 隐藏上边框 */\n"
"\n"
"}\n"
"#groupBox_23::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}\n"
"#groupBox *{}")
        self.groupBox_23.setObjectName("groupBox_23")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_18.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.webEngineView_load = QtWebEngineWidgets.QWebEngineView(self.groupBox_23)
        self.webEngineView_load.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_load.setObjectName("webEngineView_load")
        self.verticalLayout_18.addWidget(self.webEngineView_load)
        self.verticalLayout_13.addWidget(self.groupBox_23)
        self.groupBox_16 = QtWidgets.QGroupBox(self.widget_19)
        self.groupBox_16.setMinimumSize(QtCore.QSize(0, 350))
        self.groupBox_16.setMaximumSize(QtCore.QSize(480, 450))
        self.groupBox_16.setStyleSheet("QGroupBox {\n"
"    font-family: \"SimSun\";  /* 设置字体为宋体 */\n"
"    font-size: 32px;       /* 设置字体大小为18px */\n"
"    color:#00FFFF;            /* 设置字体颜色为 */\n"
"    margin-top: 2.3ex;\n"
"    border-top: 2px solid #00c6b7;         /* 隐藏上边框 */\n"
"\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}\n"
"QGroupBox *{}")
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_19.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.webEngineView_energy = QtWebEngineWidgets.QWebEngineView(self.groupBox_16)
        self.webEngineView_energy.setMinimumSize(QtCore.QSize(478, 0))
        self.webEngineView_energy.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_energy.setObjectName("webEngineView_energy")
        self.verticalLayout_19.addWidget(self.webEngineView_energy)
        self.verticalLayout_13.addWidget(self.groupBox_16)
        self.horizontalLayout_2.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.widget_22)
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_17 = QtWidgets.QGroupBox(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_17.sizePolicy().hasHeightForWidth())
        self.groupBox_17.setSizePolicy(sizePolicy)
        self.groupBox_17.setMinimumSize(QtCore.QSize(0, 680))
        self.groupBox_17.setStyleSheet("QGroupBox {\n"
"    font-family: \"SimSun\";  /* 设置字体为宋体 */\n"
"    font-size: 32px;       /* 设置字体大小为18px */\n"
"    color:#00FFFF;            /* 设置字体颜色为 */\n"
"    margin-top: 2.3ex;\n"
"    border-top: 2px solid #00c6b7;         /* 隐藏上边框 */\n"
"\n"
"}\n"
"#groupBox_17::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}\n"
"")
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_20.setContentsMargins(5, -1, 5, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.groupBox_17)
        self.webEngineView.setMinimumSize(QtCore.QSize(1400, 843))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.verticalLayout_20.addWidget(self.webEngineView)
        self.horizontalLayout_3.addWidget(self.groupBox_17)
        self.widget_2 = QtWidgets.QWidget(self.widget_20)
        self.widget_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_map = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_map.setObjectName("pushButton_map")
        self.verticalLayout_2.addWidget(self.pushButton_map)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_graph = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_graph.setObjectName("pushButton_graph")
        self.verticalLayout_2.addWidget(self.pushButton_graph)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(800, 300))
        self.groupBox_3.setMaximumSize(QtCore.QSize(3000, 320))
        self.groupBox_3.setStyleSheet("#groupBox_3 {\n"
"    border: none;\n"
"    background-color: transparent; /* 半透明背景色，RGBA中的A表示透明度 */\n"
"    border-radius: 10px; /* 可选：给widget添加圆角 */\n"
"    padding: 2px; /* 可选：给widget添加内边距 */\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setMinimumSize(QtCore.QSize(700, 0))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    font-family: \"SimSun\";  /* 设置字体为宋体 */\n"
"    font-size: 32px;       /* 设置字体大小为18px */\n"
"    color:#00FFFF;            /* 设置字体颜色为 */\n"
"    margin-top: 2.3ex;\n"
"    border-top: 2px solid #00c6b7;         /* 隐藏上边框 */\n"
"\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.webEngineView_2 = QtWebEngineWidgets.QWebEngineView(self.groupBox_2)
        self.webEngineView_2.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_2.setObjectName("webEngineView_2")
        self.verticalLayout_6.addWidget(self.webEngineView_2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setMinimumSize(QtCore.QSize(600, 0))
        self.groupBox_13.setMaximumSize(QtCore.QSize(2000, 350))
        self.groupBox_13.setStyleSheet("QGroupBox {\n"
"    font-family: \"SimSun\";  /* 设置字体为宋体 */\n"
"    font-size: 32px;       /* 设置字体大小为18px */\n"
"    color:#00FFFF;            /* 设置字体颜色为 */\n"
"    margin-top: 2.3ex;\n"
"    border-top: 2px solid #00c6b7;         /* 隐藏上边框 */\n"
"\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}\n"
"")
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_9.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.webEngineView_3 = QtWebEngineWidgets.QWebEngineView(self.groupBox_13)
        self.webEngineView_3.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_3.setObjectName("webEngineView_3")
        self.verticalLayout_9.addWidget(self.webEngineView_3)
        self.horizontalLayout.addWidget(self.groupBox_13)
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_control = QtWidgets.QPushButton(self.widget)
        self.pushButton_control.setMaximumSize(QtCore.QSize(134, 16777215))
        self.pushButton_control.setObjectName("pushButton_control")
        self.verticalLayout.addWidget(self.pushButton_control)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addWidget(self.widget_20)
        self.verticalLayout_17.addWidget(self.widget_22)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "考虑碳电储耦合的新型电力系统智能调度优化软件"))
        self.groupBox.setTitle(_translate("Form", "热点词"))
        self.groupBox_23.setTitle(_translate("Form", "负荷量"))
        self.groupBox_16.setTitle(_translate("Form", "储能占比"))
        self.groupBox_17.setTitle(_translate("Form", "地图"))
        self.pushButton_map.setText(_translate("Form", "湖北省"))
        self.pushButton.setText(_translate("Form", "武汉市"))
        self.pushButton_3.setText(_translate("Form", "宜昌市"))
        self.pushButton_4.setText(_translate("Form", "咸宁市"))
        self.pushButton_graph.setText(_translate("Form", "关系图"))
        self.groupBox_2.setTitle(_translate("Form", "发电侧日出力结果"))
        self.groupBox_13.setTitle(_translate("Form", "碳价历史曲线图"))
        self.pushButton_control.setText(_translate("Form", "控制窗"))
        self.pushButton_5.setText(_translate("Form", "参数寻优"))
        self.pushButton_6.setText(_translate("Form", "数据分析"))
        self.pushButton_7.setText(_translate("Form", "数据更新"))
from PyQt5 import QtWebEngineWidgets
