# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_two(object):
    def setupUi(self, page_two):
        page_two.setObjectName("page_two")
        page_two.resize(2107, 1173)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(page_two.sizePolicy().hasHeightForWidth())
        page_two.setSizePolicy(sizePolicy)
        page_two.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"#page_two{\n"
" background-color:#0F192A\n"
"}\n"
"\n"
"QGraphicsView {\n"
"    background: transparent;   /* 设置背景为透明 */\n"
"    border: none;               /* 去除边框 */\n"
"}\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(page_two)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_6 = QtWidgets.QWidget(page_two)
        self.widget_6.setStyleSheet("QGroupBox {\n"
"    font-family: \"SimSun\";  /* 设置字体为宋体 */\n"
"    font-size: 32px;       /* 设置字体大小为18px */\n"
"    color:#00FFFF;            /* 设置字体颜色为 */\n"
"    margin-top: 2.3ex;\n"
"    border-top: 2px solid #00c6b7;         /* 隐藏上边框 */\n"
"\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_6)
        self.widget.setObjectName("widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_part1 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_part1.setStyleSheet("QPushButton {\n"
"    background-color: #1D2B3A;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 16px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为深色 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果 */\n"
"}")
        self.pushButton_part1.setObjectName("pushButton_part1")
        self.horizontalLayout_5.addWidget(self.pushButton_part1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pushButton_part2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_part2.setStyleSheet("QPushButton {\n"
"    background-color: #1D2B3A;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 16px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为深色 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果 */\n"
"}")
        self.pushButton_part2.setObjectName("pushButton_part2")
        self.horizontalLayout_5.addWidget(self.pushButton_part2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pushButton_part3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_part3.setStyleSheet("QPushButton {\n"
"    background-color: #1D2B3A;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 16px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为深色 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果 */\n"
"}")
        self.pushButton_part3.setObjectName("pushButton_part3")
        self.horizontalLayout_5.addWidget(self.pushButton_part3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #1D2B3A;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 16px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为深色 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果 */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_9.addItem(spacerItem5)
        self.pushButton_plot = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_plot.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_plot.setStyleSheet("QPushButton {\n"
"    background-color: #1D2B3A;      /* 深蓝色背景 */\n"
"    color: white;                    /* 白色文字 */\n"
"    border: 2px solid rgba(255, 255, 255, 0.5);  /* 半透明白色边框，边框变细 */\n"
"    border-radius: 10px;             /* 圆角效果 */\n"
"    padding: 10px 20px;              /* 内边距 */\n"
"    font-size: 16px;                 /* 字体大小 */\n"
"    font-weight: bold;               /* 加粗字体 */\n"
"    transition: background-color 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A5B73;       /* 悬停时背景变浅 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 悬停时边框颜色稍微变深 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C3E50;       /* 按钮按下时背景变为深色 */\n"
"    border-color: rgba(255, 255, 255, 0.7);  /* 按下时边框颜色 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);  /* 按下时添加阴影效果 */\n"
"}")
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.verticalLayout_9.addWidget(self.pushButton_plot, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_12.addWidget(self.widget_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem6)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(1208, 839))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    font-family: \"SimSun\";  /* 设置字体为宋体 */\n"
"    font-size: 32px;       /* 设置字体大小为18px */\n"
"    color:#00FFFF;            /* 设置字体颜色为 */\n"
"    margin-top: 2.3ex;\n"
"    border-top: 2px solid #00c6b7;         /* 隐藏上边框 */\n"
"\n"
"}\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.webEngineView_total = QtWebEngineWidgets.QWebEngineView(self.groupBox)
        self.webEngineView_total.setMinimumSize(QtCore.QSize(0, 820))
        self.webEngineView_total.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_total.setObjectName("webEngineView_total")
        self.verticalLayout_11.addWidget(self.webEngineView_total)
        self.widget_5 = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMaximumSize(QtCore.QSize(2000, 4300))
        self.widget_5.setStyleSheet("#widget_2 {\n"
"    border: 1.5px solid #00c6b7;  /* 边框宽度为2px，边框颜色为#1D2B3A，边框类型为实线 */\n"
"    border-radius: 10px;         /* 设置圆角效果 */\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(20, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.textBrowser_out = QtWidgets.QTextBrowser(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_out.sizePolicy().hasHeightForWidth())
        self.textBrowser_out.setSizePolicy(sizePolicy)
        self.textBrowser_out.setMinimumSize(QtCore.QSize(20, 50))
        self.textBrowser_out.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_out.setFont(font)
        self.textBrowser_out.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser_out.setStyleSheet("#textBrowser_out {\n"
"    border: 2px solid #DCDCDC; /* 淡白色边框 */\n"
"    background-color: #1D2B3A; /* 背景色，适合深色主题 */\n"
"    border-radius: 10px;         /* 设置圆角效果 */\n"
"    color: white; /* 文字颜色为白色 */\n"
"    font-weight: bold; /* 文字加粗 */\n"
"    font-family: \'Times New Roman\'; /* 字体为新罗马字体 */\n"
"    font-size: 18px; /* 字体大小为 18px */\n"
"}")
        self.textBrowser_out.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.textBrowser_out.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textBrowser_out.setObjectName("textBrowser_out")
        self.horizontalLayout_2.addWidget(self.textBrowser_out)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_11.addWidget(self.widget_5)
        self.verticalLayout_12.addWidget(self.groupBox)
        self.horizontalLayout_3.addWidget(self.widget)
        self.groupBox1 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox1.setStyleSheet("#groupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 280%;                /* 将标题定位为左对齐 */\n"
"\n"
"    position: absolute;      /* 使标题绝对定位 */\n"
"    width: 200%;             /* 设置标题宽度为100% */\n"
"    margin-left: 0%;       /* 调整位置使其真正居中 */\n"
"}")
        self.groupBox1.setObjectName("groupBox1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_8 = QtWidgets.QWidget(self.groupBox1)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.webEngineView_pv = QtWebEngineWidgets.QWebEngineView(self.groupBox_2)
        self.webEngineView_pv.setMinimumSize(QtCore.QSize(385, 0))
        self.webEngineView_pv.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_pv.setObjectName("webEngineView_pv")
        self.verticalLayout_2.addWidget(self.webEngineView_pv)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.groupBox_Pgen = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_Pgen.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Pgen.setStyleSheet("#widget_Pgen {\n"
"    border: 1.5px solid #00c6b7;  /* 边框宽度为2px，边框颜色为#1D2B3A，边框类型为实线 */\n"
"    border-radius: 10px;         /* 设置圆角效果 */\n"
"}")
        self.groupBox_Pgen.setObjectName("groupBox_Pgen")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_Pgen)
        self.verticalLayout_5.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.webEngineView_Ppm = QtWebEngineWidgets.QWebEngineView(self.groupBox_Pgen)
        self.webEngineView_Ppm.setMinimumSize(QtCore.QSize(385, 0))
        self.webEngineView_Ppm.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_Ppm.setObjectName("webEngineView_Ppm")
        self.verticalLayout_5.addWidget(self.webEngineView_Ppm)
        self.verticalLayout_10.addWidget(self.groupBox_Pgen)
        self.groupBox_bat = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_bat.setStyleSheet("#widget_bat {\n"
"    border: 1.5px solid #00c6b7;  /* 边框宽度为2px，边框颜色为#1D2B3A，边框类型为实线 */\n"
"    border-radius: 10px;         /* 设置圆角效果 */\n"
"}")
        self.groupBox_bat.setObjectName("groupBox_bat")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_bat)
        self.verticalLayout_6.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.webEngineView_bat = QtWebEngineWidgets.QWebEngineView(self.groupBox_bat)
        self.webEngineView_bat.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_bat.setObjectName("webEngineView_bat")
        self.verticalLayout_6.addWidget(self.webEngineView_bat)
        self.verticalLayout_10.addWidget(self.groupBox_bat)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(self.groupBox1)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.webEngineView_w = QtWebEngineWidgets.QWebEngineView(self.groupBox_3)
        self.webEngineView_w.setMinimumSize(QtCore.QSize(385, 0))
        self.webEngineView_w.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_w.setObjectName("webEngineView_w")
        self.verticalLayout_7.addWidget(self.webEngineView_w)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.groupBox_H2 = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_H2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_H2.setStyleSheet("#widget_H2 {\n"
"    border: 1.5px solid #00c6b7;  /* 边框宽度为2px，边框颜色为#1D2B3A，边框类型为实线 */\n"
"    border-radius: 10px;         /* 设置圆角效果 */\n"
"}")
        self.groupBox_H2.setObjectName("groupBox_H2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_H2)
        self.verticalLayout_3.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.webEngineView_H2 = QtWebEngineWidgets.QWebEngineView(self.groupBox_H2)
        self.webEngineView_H2.setMinimumSize(QtCore.QSize(385, 0))
        self.webEngineView_H2.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_H2.setObjectName("webEngineView_H2")
        self.verticalLayout_3.addWidget(self.webEngineView_H2)
        self.verticalLayout_8.addWidget(self.groupBox_H2)
        self.groupBox_CAES = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_CAES.setStyleSheet("#widget_CAES {\n"
"    border: 1.5px solid #00c6b7;  /* 边框宽度为2px，边框颜色为#1D2B3A，边框类型为实线 */\n"
"    border-radius: 10px;         /* 设置圆角效果 */\n"
"}")
        self.groupBox_CAES.setObjectName("groupBox_CAES")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_CAES)
        self.verticalLayout_4.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.webEngineView_CAES = QtWebEngineWidgets.QWebEngineView(self.groupBox_CAES)
        self.webEngineView_CAES.setMinimumSize(QtCore.QSize(385, 0))
        self.webEngineView_CAES.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_CAES.setObjectName("webEngineView_CAES")
        self.verticalLayout_4.addWidget(self.webEngineView_CAES)
        self.verticalLayout_8.addWidget(self.groupBox_CAES)
        self.horizontalLayout_4.addWidget(self.widget_7)
        self.horizontalLayout_3.addWidget(self.groupBox1)
        self.horizontalLayout.addWidget(self.widget_6)

        self.retranslateUi(page_two)
        QtCore.QMetaObject.connectSlotsByName(page_two)

    def retranslateUi(self, page_two):
        _translate = QtCore.QCoreApplication.translate
        page_two.setWindowTitle(_translate("page_two", "Form"))
        self.pushButton_part1.setText(_translate("page_two", "微电网1"))
        self.pushButton_part2.setText(_translate("page_two", "微电网2"))
        self.pushButton_part3.setText(_translate("page_two", "微电网3"))
        self.pushButton_4.setText(_translate("page_two", "···"))
        self.pushButton_plot.setText(_translate("page_two", "开始绘图"))
        self.groupBox.setTitle(_translate("page_two", "源荷储整体出力情况"))
        self.label_11.setText(_translate("page_two", "总成本:"))
        self.groupBox1.setTitle(_translate("page_two", "各系统出力情况"))
        self.groupBox_2.setTitle(_translate("page_two", "太阳能"))
        self.groupBox_Pgen.setTitle(_translate("page_two", "抽水蓄能"))
        self.groupBox_bat.setTitle(_translate("page_two", "电化学储能"))
        self.groupBox_3.setTitle(_translate("page_two", "风能"))
        self.groupBox_H2.setTitle(_translate("page_two", "氢储能"))
        self.groupBox_CAES.setTitle(_translate("page_two", "压缩空气储能"))
from PyQt5 import QtWebEngineWidgets
